model_type: "SGDClassifier"
use_oversampling: false
oversampler_type: "SMOTE"
oversampler_seed: 42
train_test_split_seed: 20
cv_seed: 7
cv_splits: 5
scoring_metric: "accuracy"
search_method: "gridcv"
fixed_params:
  random_state: 42
  loss: "hinge"
  penalty: "elasticnet"
grid_search_params:
  l1_ratio: "uniform(0.0, 1.0)"
  alpha: "lognorm(0.0, 1.0)"
  max_iter: [1000, 2000]
